# Generated by Django 4.0 on 2021-12-28 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newapplication',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='newapplication',
            name='date_edited',
        ),
        migrations.AddField(
            model_name='newapplication',
            name='company_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newapplication',
            name='compensation_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newapplication',
            name='compensation_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newapplication',
            name='date_applied',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='newapplication',
            name='shift',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newapplication',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newapplication',
            name='type_of_hire',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='newapplication',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newapplication',
            name='job_title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
