# Generated by Django 4.0 on 2021-12-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jat', '0002_remove_newapplication_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
