# Generated by Django 4.0 on 2021-12-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jat', '0003_alter_newapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapplication',
            name='favorite',
            field=models.CharField(default='', max_length=10),
        ),
    ]
